version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: npm run dev-start
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/usr/src/app/src
